### ISSUE TITLE
Slider produces an error.

### ISSUE THREAD

**Issue by SvKn** [TUB-Control/PaPI#43]
1. Start PaPI
2. Create slider and change the value.
3. Following error appears

===
Traceback (most recent call last):
  File "/home/sven/PycharmProjects/PaPI/main.py", line 67, in <module>
    sys.exit(start_PaPI())
  File "/home/sven/PycharmProjects/PaPI/main.py", line 43, in start_PaPI
    core.run()
  File "/home/sven/PycharmProjects/PaPI/papi/core.py", line 195, in run
    self.__process_event__(event)
  File "/home/sven/PycharmProjects/PaPI/papi/core.py", line 456, in __process_event__
    self.__process_event_by_type__[t](event)
  File "/home/sven/PycharmProjects/PaPI/papi/core.py", line 477, in __process_data_event__
    return self.__process_data_event_l__[op](event)
  File "/home/sven/PycharmProjects/PaPI/papi/core.py", line 660, in __process_new_data__
    pl = self.core_data.get_dplugin_by_id(sub_id)
UnboundLocalError: local variable 'sub_id' referenced before assignment

**Comment by SvKn** [comment]
Done
